version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  lint:
    docker:
      - image: circleci/python:3.9-buster
    steps:
      - checkout
      - run:
          name: Lint with pre-commit
          command: |
            sudo pip install --upgrade pre-commit==2.15.0
            pre-commit run --all-files
  test-and-build:
    docker:
      - image: circleci/python:3.9-buster
    environment:
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build test image
          command: |
            cp .env-build .env
            DOCKER_BUILDKIT=1 ./bin/dc.sh build --progress=plain test
      - run:
          # copy synonym files to elasticsearch7 container, since circleci doesn't support volume mounts:
          # https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
          name: Copy synonym files to elasticsearch7
          command: |
            ./bin/dc.sh up -d elasticsearch7
            docker cp ./kitsune/search/dictionaries/synonyms/. project_elasticsearch7_1:/usr/share/elasticsearch/config/synonyms
      - run:
          name: Run unit tests
          command: ./bin/dc.sh run test ./bin/run-unit-tests.sh
      - run:
          name: Run js tests
          command: ./bin/dc.sh run test ./bin/run-mocha-tests.sh
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Build prod image
                command: DOCKER_BUILDKIT=1 ./bin/dc.sh build --progress=plain prod
            - run:
                name: Push prod image
                command: |
                  docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
                  source docker/bin/set_git_env_vars.sh
                  docker push mozilla/kitsune:prod-${GIT_COMMIT_SHORT}
                  docker logout
            - aws-cli/setup
            - run:
                name: Upload staticfiles
                command: |
                  source docker/bin/set_git_env_vars.sh
                  ./docker/bin/upload-staticfiles.sh
workflows:
  version: 2
  lint-test-build:
    jobs:
      - lint
      - test-and-build
